### ISSUE TITLE
Tapiriik created duplicates in Endomondo and Runkeeper

### ISSUE THREAD

**Issue by krzysieki** [cpfair/tapiriik#177] opened 2015-09-09 11:36 UTC
Hi

First, thanks for great work :)

Before tapiirik I had some trainings (the same trainings) in endomondo and in runkeeper. 

I connected dropbox, runkeeper and endomondo to tapiirik and run synchronization with default settings (sync all to all). Unfortunately activities present in endomondo and runkeeper were duplicated.

Example duplicated workouts:
Endomondo duplicates:
https://www.endomondo.com/users/15892549/workouts/592715752
https://www.endomondo.com/users/15892549/workouts/344106068

Runkeeper duplicates:
https://runkeeper.com/user/krzysieki/activity/358818632
https://runkeeper.com/user/krzysieki/activity/645979668

Above should be one workout in Endo and one workout in Runkeeper.

Another question is what is the best way to resolve duplicates? So that I can still use tapiriik. I know that I have to delete duplicates manually but should I delete duplicates in all services (runkeeper, endomondo, dropbox)? In dropbox I can't figure out which file is responsible for which workout.

**Comment by cpfair** [comment] 2015-09-10 15:36
Generally when this happens it's due to a problem with timezones (either bad data, or a mistake with the automatic lookup) - so the two activities appear several hours apart, and get treated as separate. Unfortunately the logs rotate quickly so I can't confirm this,

**Comment by natelowry** [comment] 2015-10-01 13:18
Is there an easier way to bulk delete all the duplicates created by Tapiriik?  I synced to dropbox and it duplicated all of my workouts since July (I think it changed the sport type from Cycling, Transport to Cycling, Sport?) and going through those one-by-one sounds terrible.  It really messed up my history :frowning:

**Comment by demonhell** [comment] 2015-10-16 06:17
It Happened to me just 36hours ago (Wednesday 23.30 GMT+2)  
On a today check I found many of the successfully synced workouts duplicated (an hundred).

Connection between endomondo and dropbox
Eg:
Original:
https://www.endomondo.com/users/2573919/workouts/603016511
Clone: https://www.endomondo.com/users/2573919/workouts/618255860

Cloned workouts have no comments nor tags. Time seems to be equal on both.

My workouts are not public (visible only to friends).
Let me know if you need any more detail. 

As natelowry, I kindly ask a way to automatically remove the duplicated workouts

**Comment by demonhell** [comment] 2015-10-16 06:23
Sorry to bother with a useless comment but I needed to say: Besides this issue, tapiriik is a great idea and as a developer,  I love it's  open-source nature.
#MyDataAreMine

**Comment by natelowry** [comment] 2015-10-17 22:10
@demonhell did you happen to notice if it seemed to only happen on "Cycling, Transport" rides and if it duplicated them as "Cycling, Sport"? Might help nail down the issue.

**Comment by demonhell** [comment] 2015-10-19 07:14
@natelowry it Happened on a mix of workout-types: hiking,  running,  mountain-bike (don't know the exact translation.  I don't have the gpx with me at the moment) 
I suspect it has Cloned every workout with GPS data. (fortunately dropbox has a api usage limit and the damage is manageable)

On a late though: the morning after that night I re-launched the sync to extract the remaining workouts, But I don't know which sync caused the issue cause I noticed it only when I wrote here

**Comment by perina** [comment] 2015-10-19 16:45
@natelowry I can confirm items named "Cycling, Transport" were doubled in Endomondo linked to Strava while other cycling was not....

**Comment by rxbrad** [comment] 2015-12-15 19:35
My runs in Endomondo also just got duplicated.  It appears that it took all of my runs that I didn't put a label on, added a new label ("Morning Run" since I always run in the morning), and added it as a dupe to the existing version.

Example:
Original Run: https://www.endomondo.com/users/7100118/workouts/592387060
Duplicated Version: https://www.endomondo.com/users/7100118/workouts/644582696

**Comment by hugtom** [comment] 2016-01-04 11:41
I came here having experienced the same issue with duplicates and searching for answers.

I log workouts in Endomondo and set up a sync to Dropbox and Strava. Duplicates appeared after my initial sync in Endomondo, for all types of workouts (runs, walks, cycling sport and cycling transport) between certain dates (not consistently throughout the calendar). Duplicates do not appear in Strava or Dropbox.

Deleting the duplicates is tedious and I contacted Endomondo for advice on a bulk delete. They weren't able to help but had one potentially useful piece of advice: to set up one-way syncing from Endomondo to Strava and Dropbox, don't set up syncing back from Strava/Dropbox. Open the syncing preferences on your 'recipient' accounts and uncheck the 'sync to' options.

This works OK for me as I am only logging workouts on one service. Would have been good to know before the first sync, as maybe duplicates would have been avoided. Endomondo recommended setting up one-way syncing to avoid duplicates reappearing later.

Hope this helps someone.

**Comment by mfurgal** [comment] 2016-07-10 18:30
I'm using tapiriik for last couple of days. First batch of activities was synchronized without problems. What I noticed today is that older activities (not synchronized in first run) on Endomondo got doubled.

I have all but one activities on Endomondo and synchronize with Strava and Dropbox.

**Comment by Fandekasp** [comment] 2016-07-26 01:36
I'm having a lot of duplicated data after syncing runkeeper to tapiriik yesterday
![screenshot-2016-07-26_10-12-24](https://cloud.githubusercontent.com/assets/260983/17123025/962ecede-531b-11e6-83bd-a6ded71155dc.png)


Somehow, the duplicates are shown 0.2~0.3km longer, and a day earlier
![screenshot-2016-07-26_10-32-48](https://cloud.githubusercontent.com/assets/260983/17123144/713644d0-531c-11e6-89cc-09cd63b76183.png)

This is really messing with my data. Can you work on something to fix it?
* If you see different timezones across services, trigger an alert to ask us to fix it
* Add a scoring function to analyze activities closed in time, and raise warnings when close activities are abnormaly similar.

Anyways, I'm very happy to see a service like tapiriik emerging, looking forward to seeing it become bug-free soon.

**Comment by patrickplaggenborg** [comment] 2016-07-26 16:51
Last week a lot of my activities were duplicated as well on Runkeeper using Tapiriik.

Running activities were duplicated as running.
Hiking activities were duplicated as running.
Cycling activities were duplicated as running.

All activities had exactly the same GPS map In the duplicate. Some were 0.2-0.3 km longer or shorter.

I also noticed in the duplicate activity the map was set to 'private' while my originals had a public map.

Also, all duplicates did not contain any heartrate graph, or did contain one that seemed weird and had 3 or 4 measurements.

I removed the duplicates for all activities (many!) and it seems stable now.

It does still happen for every new activity though.

**Comment by eivindorama** [comment] 2016-09-12 11:17
Same issue (or a very similar issue) with Garmin Connect / Runkeeper / Dropbox -- I now have on the order of a hundred duplicated workouts across these services, and as far as I can see no way to fix that short of manually going through all my workouts and eliminating duplicates.

Some of these "duplicates" are very close matches rather than identical, i.e. one might be for 9.53km worth of running between 10:17 and 11:07 while the other is for 9.51km of running between 10:17 and 11:06 -- so they might be activities that existed in very similar, but not identical, form on both services before tapiriik synced.

But really, Tapiriik should treat "very similar" as likely duplicates. If you log the same activity to two different services two different ways, the activities won't be identical, but very close. (in my case I've got a Garmin watch that sends things to Garmin Connect, and at the same time sometimes use Runkeeper on my phone)

**Comment by Donostio** [comment] 2017-01-20 11:55
Same here, nightmare to fix. The FAQ really shouldn't say that Tapiriik doesn't create duplicates until this is stopped.

**Comment by krzysieki** [comment] 2017-01-30 22:04
Yeah I spent few hours to fix it manually.

Tapiriik works great but now I always choose one way sync (i.e. from Endomondo to Runkeeper)

@cpfair please update docs and faq so that users know that sync all to all option would (probably) create duplicates

**Comment by natelowry** [comment] 2017-02-19 22:40
I have a possible fix here if anyone else can :eyes: and test it https://github.com/cpfair/tapiriik/pull/296

**Closed** 2017-02-20 19:07 UTC

**Comment by pmccraken** [comment] 2017-06-02 21:37
Tapiriik is still duplicating my Endomondo workout when the settings I have are only for Endomondo to send activities to other sites. The workout is captured with the IOS app but then when sync happens I get another copy of the activity. Any ideas?

**Comment by natelowry** [comment] 2017-06-03 01:16
@pmccraken do you happen to know what the workout type is?

**Comment by pmccraken** [comment] 2017-06-03 12:48
@natelowry It's happening with all the cycling and running activities I capture through the Endomondo IOS app. I've tried one way sync from Strava to Endomondo and now one way sync from Endomondo to Strava but they both result in duplicated activities in Endomondo.

**Comment by natelowry** [comment] 2017-06-05 13:48
Hmmm...that's really weird.  So, you're sure you only have it sending from Endo to other sites? 😛 Can you try adding a manual activity on the web with the same type and see if it does it?

Also, to clarify, it's duplicating them back into Endomono only? or duplicating them on all sites?  

Can you check the workouts in Endomondo and see if you can spot the difference in the two?

Sorry I might be out of my expertise here, but hopefully these questions might help figure something out.

**Comment by pmccraken** [comment] 2017-06-07 20:16
Thanks for getting back to me anyway.

I've just added two manual activities to Endomondo. Let's see what happens - 54 mins until next sync
I'll do some analysis on the duplicated activities - as you can see from screen shots I have Endomondo as the golden source.
![image](https://user-images.githubusercontent.com/1822845/26899048-d0c7311e-4bc5-11e7-9016-7eaa38fae94d.png) ![image](https://user-images.githubusercontent.com/1822845/26899108-08dfa298-4bc6-11e7-9052-22d8722f2ffd.png) ![image](https://user-images.githubusercontent.com/1822845/26899093-fa6013e2-4bc5-11e7-8bb2-ca466b286214.png) 
![image](https://user-images.githubusercontent.com/1822845/26899127-1996c95e-4bc6-11e7-9293-2db2fcc81e80.png)

**Comment by pmccraken** [comment] 2017-06-07 20:27
Hmmm... I think I may know what's up. I have Garmin connect as a connected app within Endomondo. I wonder if by sending Endomondo activities to Garmin using Tapiriik it's causing Garmin connect to reflect them back. I've turned off Garmin connect from Endomondo. I'll see if that fixes it.

**Comment by natelowry** [comment] 2017-06-07 20:55
![image](http://www.reactiongifs.com/wp-content/uploads/2012/11/fingers-crossed.gif)

nice detective work either way

**Comment by patrickplaggenborg** [comment] 2017-06-08 08:36
I had the exact same problem with duplicates to Runkeeper.

I had Garmin connected as well.

Tapiriik posted to Garmin + Runkeeper + Strava

Garmin itself then re-posted to Runkeeper with slightly modified data, causing a duplicate.

I disabled Garmin export entirely (as I don’t actively use it). This solved it. There might be ways to simply remove the Garmin to Runkeeper or Endomondo connection as well.
