### ISSUE TITLE
Support Runtastic

### ISSUE THREAD

**Issue by sylr** [cpfair/tapiriik#118] opened 2015-03-27 10:48 UTC
Would be brilliant if you could add runtastic support.

Cheers.

**Comment by santiacho** [comment] 2015-06-02 07:27
+1

**Comment by jacinmontava** [comment] 2015-06-02 10:53
+1

**Comment by jmiba** [comment] 2015-06-02 12:22
+1

**Comment by deichcode** [comment] 2015-06-11 23:33
+1

**Comment by mindrunner** [comment] 2015-06-13 04:08
+1

**Comment by xurban42** [comment] 2015-06-19 12:43
+1

**Comment by cpfair** [comment] 2015-06-19 12:48
Duplicate of #95

**Closed by cpfair** 2015-06-19 12:48 UTC

**Comment by gauravarora** [comment] 2015-09-10 10:17
+1

**Comment by Gearlux** [comment] 2015-12-05 17:07
+1

**Comment by harroguk** [comment] 2016-03-08 14:23
+1

**Comment by fazyloff** [comment] 2016-08-01 06:46
+1
